services:
  jenkins:
    container_name: Jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    container_name: SSH-Agent
    image: jenkins/ssh-agent
  tomcat:
    container_name: Tomcat
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    ports:
      - '4287:4287'
    volumes:
      - tomcat_logs:/usr/local/tomcat/logs/
    env_file:
      - './tomcat/compose.env'
  ansible:
    container_name: Ansible
    hostname: ansible-server
    privileged: true
    build:
      context: ./ansible
      dockerfile: Dockerfile
    ports:
      - '5200:5200'
    volumes:
      - ./ansible/data:/home/ansible
      - ./ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible/hosts:/etc/ansible/hosts
      - ./ansible/tomcat:/tomcat
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=false
      - ANSIBLE_CONFIG=/etc/ansible/ansible.cfg
volumes:
  jenkins_home:
  tomcat_logs:
  ansible_data:
