services:
  jenkins:
    container_name: Jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    container_name: SSH-Agent
    image: jenkins/ssh-agent
  tomcat:
    container_name: Tomcat
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    ports:
      - '4287:4287'
    volumes:
      - tomcat_logs:/usr/local/tomcat/logs/
    env_file:
      - './tomcat/compose.env'
  ansible:
    container_name: Ansible
    build:
      context: ./ansible
      dockerfile: Dockerfile
    volumes:
      - ./ansible/data:/ansible
    # command:
    #   [
    #     'ansible-playbook',
    #     'playbook.yml',
    #     'ansible-playbook',
    #     '--version',
    #     'tail',
    #     '-f',
    #     '/dev/null',
    #   ]
volumes:
  jenkins_home:
  tomcat_logs:
  ansible_data:
