- hosts: localhost
  connection: local
  tasks:
    - name: Build Docker image
      command: sudo docker build -t tomcat-regapp:latest .
      args:
        chdir: /tomcat
    - name: Tag docker image for push 
      command: sudo docker tag tomcat-regapp:latest darkmatter08/tomcat-regapp:latest

    - name: push docker image to docker hub
      command: sudo docker push darkmatter08/tomcat-regapp:latest

 