- hosts: localhost
  connection: local
  tasks:
    - name: Build Docker image
      command: sudo docker build -t tomcat-regapp:latest .
      args:
        chdir: /tomcat
    - name: Tag docker image for push 
      command: sudo docker tag tomcat-regapp:latest darkmatter08/tomcat-regapp:latest

    - name: Log in to Docker Hub
      docker_login:
        username: darkmatter08
        password: Nixo2018

    - name: push docker image to docker hub
      command: docker push darkmatter08/tomcat-regapp:latest

 