gossfile:
  goss2.yaml: {}
command:
  ansible:
    exit-status: 0
    exec: "ansible --version"
    timeout: 30000
  ansible-lint:
    exit-status: 0
    exec: "ansible-lint --version"
    timeout: 30000
  bash:
    exit-status: 0
    exec: "bash -version"
  curl:
    exit-status: 0
    exec: "curl --version"
  docker:
    exit-status: 0
    exec: "docker help"
  git:
    exit-status: 0
    exec: "git version"
  pip:
    exit-status: 0
    exec: "pip3 -V"
  python:
    exit-status: 0
    exec: "python --version"
  rsync:
    exit-status: 0
    exec: "rsync --version"
  ssh:
    exit-status: 0
    exec: "ssh -V"
  vault:
    exit-status: 0
    exec: "vault -version"
