---
name: donaldrich/ansible:latest
usage: Lightweight image for developing and executing Ansible playbooks

tasks:
  validate:
    usage: goss validation of installed packages
    run: goss validate --color --format documentation

  environment:
    usage: print env variables
    run:
      - command:
          exec: printenv
          print: "\e[32mprintenv\e[0m"
  version:
    usage: check package versions
    run:
      - command:
          exec: ansible --version
          print: "\e[32mAnsible\e[0m"
      - command:
          exec: ansible-lint --version
          print: "\e[32mAnsible-Lint\e[0m"
      - command:
          exec: bash -version
          print: "\e[32mBash\e[0m"
      - command:
          exec: curl --version
          print: "\e[32mCurl\e[0m"
      - command:
          exec: docker help
          print: "\e[32mDocker\e[0m"
      - command:
          exec: git version
          print: "\e[32mGit\e[0m"
      - command:
          exec: pip3 -V
          print: "\e[32mPip3\e[0m"
      - command:
          exec: python --version
          print: "\e[32mPython\e[0m"
      - command:
          exec: rsync --version
          print: "\e[32mRsync\e[0m"
      - command:
          exec: ssh -V
          print: "\e[32mSsh\e[0m"
      - command:
          exec: vault -version
          print: "\e[32mVault\e[0m"
